### PR TITLE
Add geneviewer

### PR DESCRIPTION
**Pull request by nvelden**

### CODE REVIEW

**Comment by cmdcolin** [comment]
thank you! do you think the graph label applies? i have tried to make Graph a targetted at "true graph genome" apps but i know it is a little vague

example of other graph tagged entries https://cmdcolin.github.io/awesome-genome-visualization/?latest=true&tag=Graph

**Comment by nvelden** [comment]
Ah I see. In that case I don't think the label applies since it is not an application but a tool to draw gene arrow maps. I now see that  gggenomes which is closest to my package is also not listed under Graph.

**Comment by cmdcolin** [comment]
no worries :) i went ahead and put it up now, sans- graph tag

https://cmdcolin.github.io/awesome-genome-visualization/?latest=true&selected=%23geneviewer

**Comment by cmdcolin** [comment]
could probably add a gene arrow tag or something like this too

**Comment by cmdcolin** [comment]
and a better taxonomy for the 'comparative' type apps

**Pull request merged**
