### PR TITLE
Initial gatsby config

### PR DESCRIPTION
**Pull request by cmdcolin**
I wanted to try to make a proper "SSR" version of the website so I tried out gatsby

Not too bad to get it quickstarted

Changes the TOOLS.json to a flat array, and has miscellaneous properties for

tags
platform
category
language
url
img
name

CC @tuner  curious what you think about the JSON change to a flat array

localhost_8000_ (2)

### CODE REVIEW

**Comment by cmdcolin** [comment]
The distinction between tags, categories is a little vague, but maybe ok. Perhaps category should just be the single attribute for readme organization and tags is everything else if we want to recreate the readme from json

**Comment by tuner** [comment]
Nice! Here are some thoughts!

Flat list is ok. A nested data structure supports hierarchical categories, but on the other hand, if we would like to introduce a hierarchy, it can be specified in a separate file anyway. In fact, meaningful categories or hierarchies may be difficult to devise because many tools serve multiple purposes. They would be useful for an awesome-formatted page, though.

How about having a few very broad categories such as: desktop/web app, library/package, command line, web service/database/portal, exotic. This is actually pretty much the same as `platform`. But then we have a problem with tools such as JBrowse, which can be used as a standalone app or an embeddable library...

`tags` is quite ambiguous because it has no proper semantics. Howabout having a `purpose` property, which could have tags like: SV, BAM, Hi-C, Single cell, ...

**Comment by cmdcolin** [comment]
this is a pretty interesting. It is definitely true tags are quite vague, but sometimes I wonder if it is a good enough system just because it can be so general? I ended up with this in the json

tags
platform
language

I made filters for these also...there end up being a lot of platforms, languages, and tags, but I tried to make a couple buttons up top that reproduce the general README  categories, but tries to avoid putting them in any specific high level category


https://cmdcolin.github.io/awesome-genome-visualization

**Comment by cmdcolin** [comment]
maybe we can merge for now but I am also definitely fine to consider changes to the schema too :)

**Comment by tuner** [comment]
Whoa! Tons of screenshot! So awesome! ❤️ 

The layout looks terrible on mobile, though. If you don't mind, I could implement a nice responsive layout at some point?

**Comment by cmdcolin** [comment]
Ah yes. Better mobile design definitely welcome. I just put a small patch in with a media query to try to help layout on mobile but it's definitely not there yet

**Pull request merged**
