### PR TITLE
modest facelift and better mobile behavior

### PR DESCRIPTION
**Pull request by tuner**
Hi,

This should now behave nicely on mobile. I also did a modest facelift, but it could be developed further...

In summary:
* Long links are truncated
* Images open in a modal when clicked
* Images behave better with different viewport widths
* A bit more "fresh" color (well, shades of gray) scheme
* Filter dropdows are nicely aligned and not so tightly packed
* Adjusted margins and paddings here and there to make everything a bit more aligned
* Adjusted link colors and decorations. The colors could be even better, though.
* Probably something more

What do you think?

This could be prettified even more. For example:
* Nicer header section (including all the filters and other stuff)
* Nicer font
* An awesome logo!
* Tags could look like, u know, tags.
* Etc...

### CODE REVIEW

**Comment by cmdcolin** [comment]
Picture of 2.

Screenshot from 2021-03-31 17-56-52

there is whitespace to the right of the cards that maybe could be used more on mobile?

**Comment by cmdcolin** [comment]
for 3. I like taking screenshots with ctrl+shift+p with devtools open and going to screenshot, but with this branch it makes all the fonts very large like this. could be more weird and not necessarily a concern for users but just something i saw

localhost_8000_(iPhone 5_SE)

**Comment by tuner** [comment]
Hi @cmdcolin

I'm not sure how GitHub should be used in this case. Should I create a new pull request? Anyway, the fixes can be found in this repo/branch: https://github.com/tuner/awesome-genome-visualization/tree/styles

1. Thanks for pointing that out. I've never used react/JSX, although I'm familiar with the concept.
2. Oh, I had messed something up. The behaved nicely at some point but apparently I broke them and didn't test thoroughly before pushing.
3. That appears to be a chrome issue when the mobile emulation is enabled. It probably zooms the viewport (related to device pixel ratio, I guess) prior to taking the shot
4. Just handwritten. I usually use Sass, but I thought that let's keep this simple. CSS is nowadays pretty expressive with all the CSS variables and other stuff.
5. They are now shown in their native resolution and can be scrolled rightaway in mobile. On desktop, the lightbox behavior is the same.

shot

**Comment by cmdcolin** [comment]
looks great! I added this live now on the site, with a little extra diff on top to limit some sizes, to try to not let the pictures be truly full resolution, still a little bit smaller

diff: b0afbc57 (auto ran prettier on css file too)

**Pull request merged**
